//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiDang
    {
        public int MaBaiDang { get; set; }
        public Nullable<int> MaMer { get; set; }
        public Nullable<int> ViTri { get; set; }
    }
}
