//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSachMerchant
    {
        public int KhoSachMerchantID { get; set; }
        public Nullable<int> SachID { get; set; }
        public Nullable<int> MerchantID { get; set; }
        public decimal DonGia { get; set; }
        public Nullable<decimal> GiaKhuyenMai { get; set; }
        public int SoLuong { get; set; }
        public System.DateTime NgayTao { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual Merchant Merchant { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
