//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KnowledgeStoreEntities : DbContext
    {
        public KnowledgeStoreEntities()
            : base("name=KnowledgeStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<BaiDang> BaiDangs { get; set; }
        public virtual DbSet<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DbSet<ChiTietSachMerchant> ChiTietSachMerchants { get; set; }
        public virtual DbSet<CTBaiDang> CTBaiDangs { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DanhGiaCuaCustomer> DanhGiaCuaCustomers { get; set; }
        public virtual DbSet<DanhGiaCuaMerchant> DanhGiaCuaMerchants { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<GioiTinh> GioiTinhs { get; set; }
        public virtual DbSet<LichSuCu> LichSuCus { get; set; }
        public virtual DbSet<LichSuMer> LichSuMers { get; set; }
        public virtual DbSet<LoaiBia> LoaiBias { get; set; }
        public virtual DbSet<Merchant> Merchants { get; set; }
        public virtual DbSet<NangTin> NangTins { get; set; }
        public virtual DbSet<NhaXuatBan> NhaXuatBans { get; set; }
        public virtual DbSet<Sach> Saches { get; set; }
        public virtual DbSet<TheLoai> TheLoais { get; set; }
        public virtual DbSet<TinhTrangDonHang> TinhTrangDonHangs { get; set; }
    }
}
