//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class NangTin
    {
        public int MaLuotNang { get; set; }
        public int MaBaiDang { get; set; }
        public int MaMer { get; set; }
    }
}
